<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Default Response Format
    |--------------------------------------------------------------------------
    |
    | This value determines the default format of responses generated by the
    | package. You can set it to 'json' or 'xml'.
    |
    */
    'default_format' => 'json',

    /*
    |--------------------------------------------------------------------------
    | Default JSON Options
    |--------------------------------------------------------------------------
    |
    | Options for JSON encoding. You can specify JSON encoding options.
    |
    */
    'json_options' => JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE,

    /*
    |--------------------------------------------------------------------------
    | Default XML Root Element
    |--------------------------------------------------------------------------
    |
    | Defines the default root element name for XML responses.
    |
    */
    'xml_root_element' => 'response',

    /*
    |--------------------------------------------------------------------------
    | Default Status Code
    |--------------------------------------------------------------------------
    |
    | This value sets the default HTTP status code for the responses.
    |
    */
    'default_status_code' => 200,

    /*
    |--------------------------------------------------------------------------
    | Enable Detailed Error Messages
    |--------------------------------------------------------------------------
    |
    | If true, detailed error messages will be included in the response body
    | for debugging purposes. For production, you may want to set this to false.
    |
    */
    'detailed_errors' => false,

    /*
    |--------------------------------------------------------------------------
    | Response Data Wrapper
    |--------------------------------------------------------------------------
    |
    | If enabled, the response data will be wrapped in an additional 'data'
    | key. This is useful if you want a consistent structure for all responses.
    |
    */
    'wrap_data' => false,

    /*
    |--------------------------------------------------------------------------
    | Default Locale
    |--------------------------------------------------------------------------
    |
    | This value sets the default locale for the custom messages.
    |
    */
    'default_locale' => 'en',

    /*
    |--------------------------------------------------------------------------
    | Default Response Language
    |--------------------------------------------------------------------------
    |
    | Define the default language for responses.
    |     en - English
    |     pt - Portuguese
    |
    */
    'default_response_language' => 'en',

    /*
    |--------------------------------------------------------------------------
    | Response Compression
    |--------------------------------------------------------------------------
    |
    | If true, responses will be compressed to reduce payload size.
    |
    */
    'compress_responses' => false,

    /*
    |--------------------------------------------------------------------------
    | Log Responses
    |--------------------------------------------------------------------------
    |
    | If true, responses will be logged for debugging or auditing purposes.
    |
    */
    'log_responses' => false,

    /*
    |--------------------------------------------------------------------------
    | Logging Level
    |--------------------------------------------------------------------------
    |
    | Define the level of detail for logging responses (e.g., 'info', 'debug', 'error').
    |
    */
    'logging_level' => 'info',

    /*
    |--------------------------------------------------------------------------
    | API Key Header
    |--------------------------------------------------------------------------
    |
    | Define the name of the header used for API keys.
    |
    */
    'api_key_header' => 'X-API-KEY',

    /*
    |--------------------------------------------------------------------------
    | Custom Response Structure
    |--------------------------------------------------------------------------
    |
    | Define a custom structure for responses. The example below includes
    | 'status', 'message', and 'data', but you can modify this as needed.
    |
    */
    'custom_response_structure' => [
        'status' => 'status',
        'message' => 'message',
        'data' => 'data',
    ],

    /*
    |--------------------------------------------------------------------------
    | Debug Mode
    |--------------------------------------------------------------------------
    |
    | Enable or disable debug mode. When enabled, detailed error messages and
    | additional debugging information will be included in responses.
    |
    */
    'debug_mode' => false,

    /*
    |--------------------------------------------------------------------------
    | Request Logging
    |--------------------------------------------------------------------------
    |
    | If true, requests will be logged for debugging or auditing purposes.
    |
    */
    'log_requests' => false,

    /*
    |--------------------------------------------------------------------------
    | Response Time Logging
    |--------------------------------------------------------------------------
    |
    | If true, the time taken to generate responses will be logged.
    |
    */
    'log_response_time' => false,
];
